config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories do
    resources :dishes
  end

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:show, :edit, :update]
  resources :searches, only: [:show]
  resources :dishes, only: [:index] do
    resources :votes, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :votes


  def self.search(search)
    if search
      Dish.where('ingredients ILIKE ? OR title ILIKE ?', "%#{search}%", "%#{search}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :dishes
  validates :username, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dishes
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dishes, except: [:search]
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit]

  # GET categories/1/dishes
  def index
    @dishes = @category.dishes.sort_by{ |dish| dish.votes.count }.reverse
  end

  # GET categories/1/dishes/1
  def show
  end

  # GET categories/1/dishes/new
  def new
    @dish = @category.dishes.new
  end

  # GET categories/1/dishes/1/edit
  def edit
  end

  # POST categories/1/dishes
  def create
    @dish = @category.dishes.build(dish_params)
    @dish.user = current_user
    if @dish.save
      redirect_to([@dish.category, @dish], notice: 'Dish was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT categories/1/dishes/1
  def update
    if @dish.update_attributes(dish_params)
      redirect_to([@dish.category, @dish], notice: 'Dish was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE categories/1/dishes/1
  def destroy
    @dish.votes.destroy_all
    @dish.destroy

    redirect_to category_dishes_url(@category)
  end

  def search
    Dish.search(params[:search])
    # @dishes = Dish.search(params[:search])
    redirect_to category_dish_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dishes
      @category = Category.find(params[:category_id])
    end

    def set_dish
      @dish = @category.dishes.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dish_params
      params.require(:dish).permit(:title, :user_id, :prep_time, :ingredients, :directions, :category)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource,params)
    resource.update_without_password(params)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @results = Dish.search(params[:search])
    
    @appetizers = []
    @entrees = []
    @salads = []
    @desserts = []

    @results.map do |dish| 
	    if  dish.category.name == "Appetizers" 
	    	@appetizers.push(dish)
	    elsif dish.category.name == "Entrees"
	    	@entrees.push(dish) 
	    elsif dish.category.name == "Salads"
	    	@salads.push(dish)
	    elsif dish.category.name == "Desserts"
	    	@desserts.push(dish)
	    else
	    	return 0
	    end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @dish = Dish.find(params[:dish_id])
    vote = Vote.find_by(dish_id: @dish.id, user_id: current_user.id)
    if vote
      vote.destroy
    else
      Vote.create(dish_id: @dish.id, user_id: current_user.id)
    end
    if request.xhr?
      render json: { text:"#{@dish.votes.count}", id: @dish.id.to_s }
    else
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user = "ineedgravatar@gmail.com", size: 120)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/categories/index.html.erb
<!-- HOME PAGE  -->
<head>
</head>
<body id="home">
  <div class="white-bg-home">
    <div class="home-links">
      <% @categories.each do |category| %>
        <h2><%= link_to category.name, category_dishes_path(category) %></h2>
      <% end %>
    </div>
  </div>
</body>

app/views/dishes/_form.html.erb
<div class="x-up-form">
  <%= form_for([@dish.category, @dish]) do |f| %>
    <% if @dish.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

        <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title, class: "input-field input-box", placeholder: "Title" %>
    </div>

    <div class="field">
      <%= f.number_field :prep_time, id: "prep-tme", class: "input-field input-box", placeholder: "Prep Time" %>
    </div>

    <div class="field2">
      <%= f.text_area :ingredients, class: "input-longer-box", placeholder: "Ingredients" %>
    </div>

    <div class="field2">
      <%= f.text_area :directions, class: "input-longer-box", placeholder: "Directions"  %>
    </div>

    <div class="field actions">
      <%= f.submit "Create Dish", id: "submit-btn" %>
      <%= link_to 'Cancel', category_dishes_path(@dish.category), class: 'field-actions-cancel' %>
    </div>

  <% end %>
</div>

app/views/dishes/edit.html.erb
<body id="edit-dish">

  <h5>Edit Dish</h5>

  <%= render 'form' %>

  <div class="field">
    <%= link_to 'Nevermind', [@dish.category, @dish] %>
    <%= link_to 'Delete', [@dish.category, @dish], :confirm => 'Are you sure?', :method => :delete %>
  </div>
</body>

app/views/dishes/index.html.erb
<!-- SINGLE CATEGORY ALL DISHES -->
<body id="single-category">
  <div class="white-bg">
    <div class="add-dish">
     <%= link_to '+ Add a Dish', new_category_dish_path(params[:category_id]) %>
    </div>

    <div class="category-header"><%=@category.name%></div>
    <div>
      <ul>
      <% @dishes.each do |dish| %>
        <div class="dish-line">
          <div >
            <li>

              <span class="vote-count" id="vote-count-<%= dish.id %>"><%= dish.votes.count %></span> <%= render partial: "votes/vote", locals: { dish: dish } %> <span class="dish-title"><%= link_to dish.title, [dish.category, dish] %> </span>
            </li>
          </div>

          <li>
            <div class="chef-duration-left">
              Chef <%= link_to dish.user.username, user_path(dish.user) %> /
              <%= dish.prep_time %> minutes
            </div>
          </li>

        </div>

        <% end %>
      </ul>
    </div>
        <br />
    </div>
  </div>
</body>

app/views/dishes/new.html.erb
<body id="new-dish">

  <h5>New dish</h5>

  <%= render 'form' %>
</body>

app/views/dishes/show.html.erb
<body id="dish-detail">

<div class="white-bg">

<div class="content">

<div class="back-link">
  <%= link_to "Back to #{@dish.category.name}", category_dishes_path(@dish.category) %>
</div>

<h4>
  <%= @dish.title %>
</h4>

<div id="vote-and-count">
  <%= render partial: "votes/vote", locals: { dish: @dish } %>
<span class="vote-count" id="vote-count-<%= @dish.id %>"><%= @dish.votes.count %></span>
</div>

<div id="chef-and-duration">
    Chef <%= link_to @dish.user.username, user_path(@dish.user) %> /
    <%= @dish.prep_time %> minutes
</div>

<div id="directions-and-ingredients">

  <div id="directions">
    <div class="sub-header">directions</br></div>
    <%= @dish.directions %>
  </div>

  <div id="ingredients">
    <div class="sub-header">ingredients</b></div>
    <%= @dish.ingredients %>
  </div>
</div>

<% if current_user == @dish.user %>
  <%= link_to 'Edit', edit_category_dish_path(@dish.category, @dish) %>
  <%= link_to 'Back', category_dishes_path(@dish.category) %>
<% end %>

</div>

</div>

</body>

app/views/layouts/_navbar.html.erb
<div class="nav-bar">

  <div id="search-container">
     <%= form_tag("/searches/show", method: "get") do %>
     <p>
      <%= text_field_tag :search, params[:search], placeholder: "Search ingredient or recipe", size: 37 %>
       <%= submit_tag "Search", name: nil, class: "search-btn" %>
     </p>
     <% end %>
 </div>

 <div class="logo-and-text">
  <a href="/"><div class="logo">
    <%= image_tag("icon.png", size: "62x25") %>
  </div>
  <div class="logo">
    <%= image_tag("frais-logo.png", size: "55x24") %>
  </div>
  </a>
</div>

<div id="links">
  <%= link_to "Home", root_path %>
  <%unless current_user %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Login", new_user_session_path %>
  <%else%>
  <%= link_to current_user.username, current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: "delete" %>
  <%end%>
</div>
<!--Change form tag to route to different location.  -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<div class='home'>
<html>
  <title>frais</title>
  <head>

    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:300i,500,500i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon.ico' %>

    <link href="/assets/favicon.ico" rel="shortcut icon" type="images/favicon_green.png" />
  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
</div>

app/views/searches/sample-categorized-search.html.erb
<% if @results.count != 0 %>

  <h1>Appetizers</h1>
    <% @appetizers.sort_by{ |dish| dish.votes.count }.reverse.each do |result| %>
    <p>
      <%= pluralize(result.votes.count, "Vote") %> -
      <%= link_to result.title, category_dish_path(result.category, result) %>
    </p>
    <% end %>

    <h1>Entrees</h1>
     <% @entrees.sort_by{ |dish| dish.votes.count }.reverse.each do |result| %>
    <p>
      <%= pluralize(result.votes.count, "Vote") %> -
      <%= link_to result.title, category_dish_path(result.category, result) %>
    </p>
    <% end %>

    <h1>Salads</h1>
     <% @salads.sort_by{ |dish| dish.votes.count }.reverse.each do |result| %>
    <p>
      <%= pluralize(result.votes.count, "Vote") %> -
      <%= link_to result.title, category_dish_path(result.category, result) %>
    </p>
    <% end %>

    <h1>Desserts</h1>
     <% @desserts.sort_by{ |dish| dish.votes.count }.reverse.each do |result| %>
    <p>
      <%= pluralize(result.votes.count, "Vote") %> -
      <%= link_to result.title, category_dish_path(result.category, result) %>
    </p>

    <% end %>

<% else %>
  <h1>No Results Found</h1>
<% end %>

app/views/searches/show.html.erb
<h4> Search Results </h4>

<div class="white-bg" id="profile-recipes">
  <% if @results.count != 0 %>
    <ul>
      <% if @results %>

          <% @results.sort_by{ |dish| dish.votes.count }.reverse.each do |result| %>
          <div class="dish-line">
            <li>
              <span class="vote-count" id="vote-count-<%= result.id %>"><%= result.votes.count %></span> <%= render partial: "votes/vote", locals: { dish: result } %>
              <span class="dish-title"> <%= link_to result.title, category_dish_path(result.category, result) %> </span>
            </li>
          </div>
        <% end %>
      <% end %>

    </ul>
  <% else %>
    <h1>No Results Found</h1>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="profile-wrapper">
<div class="profile">
  <div class="profile-pic">
    <%= image_tag("profilepic.png") %><br>

  </div>
  <div class="profile-info">
    <h1 class="profile-username"><%= @user.username %></h1>
    <span class="profile-info-text">
      <%= pluralize(@user.dishes.count, "submitted dish") %>
    </span><br>

    <span class="profile-info-text">
      <%= pluralize(@user.dishes.map(&:votes).flatten.count, "total upvote") %>
    </span><br><br><br><br><br><br><br>

    <span class="profile-info-text">
      <% if @user == current_user %>
        <%= link_to "Edit profile", edit_user_registration_path(current_user) %>
      <% end %>
    </span>

  </div>
</div>
</div>

<div class="white-bg" id="profile-recipes">
<ul>
  <% @user.dishes.sort_by{ |dish| dish.votes.count}.reverse.each do |dish| %>
    <div class="dish-line">
      <div>
        <li>
          <span class="vote-count" id="vote-count-<%= dish.id %>"><%= dish.votes.count %></span> <%= render partial: "votes/vote", locals: { dish: dish } %> <span class="dish-title"> <%= link_to dish.title, category_dish_path(dish.category, dish) %> </span>
        </li>
      </div>

      <li>
        <div class="chef-duration-left">
          <%= dish.prep_time %> minutes
        </div>
      </li>
    </div>
  <% end %>
  </ul>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/votes/_vote.html.erb
<% if current_user && Vote.find_by(dish_id: dish.id, user_id: current_user.id) %>
   <a class="vote-link" id="arugula-<%= dish.id %>" title="Upvote" href="<%= dish_votes_path(dish) %>"><%= image_tag "arugula-green.png", :class => "arugula-effect"%></a>
<% else %>
  <a class="vote-link" id="arugula-<%= dish.id %>" title="Upvote" href="<%= dish_votes_path(dish) %>"><%= image_tag "arugula.png", :class => "arugula-effect" %></a>
 <% end %>